/* 
	contacto in table empleados
    cod dato movil
*/

CREATE DATABASE IF NOT EXISTS VETERINARIA;

USE VETERINARIA;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EMP_NOMBRE VARCHAR(50) NOT NULL,
    EMP_APELLIDO VARCHAR(50) NOT NULL,
    EMP_POR_COMISION INT NOT NULL,
    EMP_DNI INT NOT NULL,
	EMP_SUELDO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTOS (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PRD_DESCRIPCION VARCHAR(50) NOT NULL,
	PRD_STOCK INT NOT NULL,
	PRD_PRECIO_UNITARIO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS RAZAS (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RZA_DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MASCOTAS (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MSC_RAZA_ID INT NOT NULL,
	MSC_CLIENTE_ID INT NOT NULL,
    MSC_NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTES (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CLI_CUIT DOUBLE NOT NULL UNIQUE,
    CLI_NOMBRE VARCHAR(50) NOT NULL,
    CLI_DAT_FISCALES_ID INT NOT NULL,
    CLI_APELLIDO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DATOS_FISCALES (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DTF_PORCENTAJE DOUBLE NOT NULL,
    DTF_DESCRIPCION INT NOT NULL
);

CREATE TABLE IF NOT EXISTS FACTURAS (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FCT_CLIENTE_ID INT NOT NULL,
	FCT_EMPLEADO_ID INT NOT NULL,
    FCT_FECHA DATE NOT NULL,
    FCT_IVA DOUBLE NOT NULL,
    FCT_TOT_GRAL_NG DOUBLE NOT NULL,
	FCT_TOT_GRAL_FC DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS DATOS_MOVILES_FACTURA (
	ROW_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	DMF_FACTURA_ID INT NOT NULL,
    DMF_PRODUCTO_ID INT NOT NULL,
    DMF_CANTIDAD INT NOT NULL,
    DMF_DESCRPCION VARCHAR(50) NOT NULL,
	DMF_TOTAL DOUBLE NOT NULL
);

SHOW TABLES;
